//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CommitMonitor.rc
//
#define IDC_MYICON                      2
#define IDD_COMMITMONITOR_DIALOG        102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_COMMITMONITOR               107
#define IDC_COMMITMONITOR               109
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDD_URLCONFIG                   131
#define IDI_NOTIFYNEW1                  132
#define IDR_MAINDLG                     134
#define IDI_ABOUT                       135
#define IDI_ADD                         136
#define IDI_EDIT                        137
#define IDI_OPTIONS                     138
#define IDI_ICON1                       139
#define IDI_REMOVE                      139
#define IDI_ICON2                       140
#define IDI_DIFF                        140
#define IDD_OPTIONS                     141
#define IDR_TREEPOPUP                   142
#define IDR_LISTPOP                     143
#define IDR_LISTPOPUP                   143
#define IDD_FINDBAR                     144
#define IDB_CANCELNORMAL                145
#define IDC_CMVIEWER                    147
#define IDI_ICON3                       149
#define IDI_GETALL                      149
#define IDI_NOTIFYNEW0                  150
#define IDI_NOTIFYNEW2                  151
#define IDI_NOTIFYNEW3                  152
#define IDI_PARENTPATHFOLDER            153
#define IDI_PARENTPATHFOLDEROPEN        154
#define IDI_REPOURL                     155
#define IDI_ICON5                       156
#define IDI_REPOURLNEW                  156
#define IDR_LISTPOPUPTSVN               157
#define IDD_NEWERNOTIFYDLG              158
#define IDI_ICON4                       159
#define IDI_REPOURLFAIL                 159
#define IDI_REPOURLINACTIVE             160
#define IDD_PASSWORD                    161
#define IDB_PNG1                        162
#define IDB_COMMITMONITOR               162
#define IDI_ICON6                       163
#define IDI_MARKASREAD                  163
#define IDR_TREEPOPUPTSVN               164
#define IDC_MONITOREDURLS               1000
#define IDC_ADDURL                      1001
#define IDC_EDIT                        1002
#define IDC_URLEDIT                     1002
#define IDC_URLTREE                     1004
#define IDC_URLTOMONITOR                1005
#define IDC_CHECKURL                    1006
#define IDC_CHECKTIME                   1007
#define IDC_CREATEDIFFS                 1008
#define IDC_PROJECTNAME                 1009
#define IDC_LOGINFO                     1010
#define IDC_USERNAME                    1011
#define IDC_PASSWORD                    1012
#define IDC_SHOWDIFF                    1013
#define IDC_BUTTON1                     1014
#define IDC_URLDELETE                   1014
#define IDC_DIFFBROWSE                  1014
#define IDC_FINDNEXT                    1014
#define IDC_TASKBAR_ALWAYSON            1015
#define IDC_AUTOSTART                   1016
#define IDC_DIFFVIEWER                  1017
#define IDC_EXIT                        1018
#define IDC_FINDTEXT                    1019
#define IDC_FINDPREV                    1020
#define IDC_MATCHCASECHECK              1021
#define IDC_FINDEXIT                    1022
#define IDC_NOTIFICATIONSOUNDPATH       1023
#define IDC_SOUNDBROWSE                 1024
#define IDC_INFOLABEL                   1025
#define IDC_ANIMATEICON                 1026
#define IDC_NOTIFICATIONSOUND           1027
#define IDC_BUTTON2                     1028
#define IDC_EXPORT                      1028
#define IDC_VERSIONLABEL                1029
#define IDC_IMPORT                      1029
#define IDC_WEBLINK                     1030
#define IDC_DIFFVIEWERLABEL             1031
#define IDC_IGNORESELF                  1032
#define IDC_CHECK1                      1033
#define IDC_USETSVN                     1033
#define IDC_EXECUTEIGNORED              1033
#define IDC_WEBURL                      1034
#define IDC_CHECKNEWER                  1035
#define IDC_IGNOREUSERS                 1036
#define IDC_SCRIPT                      1037
#define IDC_WEBDIFF                     1038
#define IDC_NUMLOGLABEL                 1039
#define IDC_INCLUDEUSERS                1039
#define IDC_NUMLOGS                     1040
#define IDC_CHECK2                      1041
#define IDC_NOTIFYCONNECTERROR          1041
#define IDC_FILTERSTRING                1042
#define IDC_FILTERLABEL                 1043
#define IDC_MAXLOGENTRIES               1044
#define IDC_CHECK3                      1045
#define IDC_LEFTMENU                    1045
#define IDC_PW1                         1046
#define IDC_PW2                         1047
#define IDC_INFOLABEL2                  1047
#define IDC_AEROLABEL                   1048
#define IDC_URLGROUP                    1049
#define IDC_IGNOREEOL                   1050
#define IDC_IGNORESPACES                1051
#define IDC_IGNOREALLSPACES             1052
#define IDC_DIFFOPTIONS                 1056
#define IDC_                            1057
#define IDC_WEBVIEWER                   1057
#define ID_FILE_OPENCOMMITMONITOR       32771
#define ID_MAIN_OPENCOMMITMONITOR       32772
#define ID_POPUP_OPENCOMMITMONITOR      32773
#define ID_MAIN_ADDPROJECT              32774
#define ID_MAIN_EDIT                    32775
#define ID_MAIN_REMOVE                  32776
#define ID_MAIN_SHOWDIFF                32777
#define ID_MISC_OPTIONS                 32778
#define ID_MISC_ABOUT                   32779
#define ID_POPUP_EDIT                   32780
#define ID_POPUP_REMOVE                 32781
#define ID_POPUP_SHOWDIFF               32782
#define ID_POPUP_REMOVE32783            32783
#define ID_POPUP_MARKALLASREAD          32784
#define IDM_SHOWFINDBAR                 32787
#define IDM_FINDNEXT                    32789
#define IDM_FINDPREV                    32790
#define IDM_FINDEXIT                    32793
#define ID_MAIN_CHECKREPOSITORIESNOW    32794
#define ID_POPUP_SHOWDIFFWITHTORTOISESVN 32797
#define ID_MAIN_SHOWDIFFTSVN            32798
#define ID_POPUP_MARKNODEASREAD         32799
#define ID_POPUP_CHECKNOW               32800
#define ID_POPUP_ADDPROJECT             32801
#define ID_POPUP_OPTIONS                32802
#define ID_POPUP                        32803
#define ID_MAIN_SHOWDIFFCHOOSE          32804
#define ID_POPUP_OPENWEBVIEWER          32805
#define ID_POPUP_REFRESHALL             32806
#define ID_POPUP_ACTIVE                 32807
#define ID_POPUP_MARKASUNREAD           32813
#define ID_POPUP_MARKASUNREAD32814      32814
#define ID_POPUP_MARKALLASREAD32815     32815
#define ID_POPUP_CHECKNOW32816          32816
#define ID_POPUP_ADDPROJECT32817        32817
#define ID_POPUP_ADDPROJECTWITHTEMPLATE 32818
#define ID_MAIN_COPY                    32819
#define ID_POPUP_COPYTOCLIPBOARD        32821
#define ID_POPUP_COPYTOCLIPBOARD32822   32822
#define ID_POPUP_REPOSITORYB            32823
#define ID_POPUP_SHOWLOG                32824
#define ID_POPUP_REPOBROWSER            32825
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32836
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
